language: c

script:
  - ./get-build-script.sh
  - ./r-build.sh

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - travis

env:
  global:
    secure: DX0K2Bld0uaSAIehbCGhdimzB2ntINOfq4KHjCKIIEh3nHvXyhWIttTrh2S2HhQGQuHLfYUZ5OWOUqLuqCjHVeAV/oDa+eWZzf6OPSqAJAib/wrvZAcUEu/GcbYUH3XVrw/tuZI5NumaDn1aQPuOSK6oGB/DpUmkYTIzWkNcDY0=
