
language: c

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/bintex/pkg-build.sh
  - chmod 755 pkg-build.sh
  - cp pkg-build.sh rbuildertest
  - cd rbuildertest
  - ./pkg-build.sh bootstrap

install:
  - ./pkg-build.sh install_deps

script:
  - ./pkg-build.sh run_build
  - ./pkg-build.sh run_check

after_failure:
  - ./pkg-build.sh dump_logs

after_success:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=3.0.3
    - RVERSION=3.1.0
    - RVERSION=3.1.1
    - RVERSION=3.1.2
    - RVERSION=devel
  global:
    - BOOTSTRAP_LATEX=true
    - R_BUILD_ARGS=" "
    - R_CHECK_ARGS="--as-cran"
